/// Flutter icons MyFlutterApp
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';

  static const IconData caffiene = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData calcium = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData calories = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData carbohydrates = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData copper = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData fat = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData fiber = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData folate = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData iron = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData magnesium = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData manganese = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData phosphorous = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData potassium = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData protein = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData saturated_fat = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData selenium = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData sodium = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData sugar = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData total_cholestorol = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData vitamin_b1 = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData vitamin_b2 = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData vitamin_b3 = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData vitamin_b5 = const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData vitamin_b6 = const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData vitamin_b12 = const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData vitamin_c = const IconData(0xe819, fontFamily: _kFontFam);
  static const IconData vitamin_e = const IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData zinc = const IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData ingredients = const IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData diet = const IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData steps = const IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData cuisine = const IconData(0xe820, fontFamily: _kFontFam);
}
